import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";
import Link from "next/link"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SUPPONPON",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="header">
          <div className="header-container">
            <a className="logo" href="/">
              <Image
                src="/images/header_suppon.png" 
                width={60}
                height={60}
                alt="SUPPONPON logo" 
                className="logo-img"
              />
              <span className="logo-text">SUPPONPON</span>
            </a>
            <nav className="nav">
              <a href="/">出席確認お役立ちサイト</a>
            </nav>
            <Link href="http://localhost:3000/form">
            <button className="post-button">
              投稿はこちら
              <svg className="icon" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </button>
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}